services:
  api:
    image: nxsgpt:latest
    container_name: nxsGPT-Custom
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - MONGO_URI=mongodb://mongodb:27017/nxsGPT
      - APP_TITLE=nxsGPT
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - ./client/public/assets:/app/client/public/assets
      - ./.env:/app/.env
