# N8N Integration Docker Compose Override
# This file extends the base LibreChat docker-compose.yml with N8N services
# Usage: docker-compose -f docker-compose.yml -f docker-compose.n8n.yml up

networks:
  n8n_network:
    external: false

volumes:
  n8n_storage:
  postgres_n8n_storage:
  ollama_storage:
  qdrant_storage:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['default', 'n8n_network']
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres_n8n
    - DB_POSTGRESDB_USER=${N8N_POSTGRES_USER:-n8n}
    - DB_POSTGRESDB_PASSWORD=${N8N_POSTGRES_PASSWORD:-n8npassword}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-myEncryptionKey}
    - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_JWT_SECRET:-myJwtSecret}
    - OLLAMA_HOST=ollama:11434
    - N8N_SECURE_COOKIE=false

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: n8n-ollama
  networks: ['n8n_network']
  restart: unless-stopped
  ports:
    - "11434:11434"
  volumes:
    - ollama_storage:/root/.ollama

services:
  # Extend the API service to expose N8N URL as environment variable
  api:
    environment:
      - N8N_URL=http://n8n:5678
      - REACT_APP_N8N_URL=http://localhost:5678

  # PostgreSQL for N8N
  postgres_n8n:
    image: postgres:16-alpine
    hostname: postgres_n8n
    container_name: n8n-postgres
    networks: ['n8n_network']
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${N8N_POSTGRES_USER:-n8n}
      - POSTGRES_PASSWORD=${N8N_POSTGRES_PASSWORD:-n8npassword}
      - POSTGRES_DB=${N8N_POSTGRES_DB:-n8n}
    volumes:
      - postgres_n8n_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${N8N_POSTGRES_USER:-n8n} -d ${N8N_POSTGRES_DB:-n8n}']
      interval: 5s
      timeout: 5s
      retries: 10

  # N8N Import service
  n8n-import:
    <<: *service-n8n
    hostname: n8n-import
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/demo-data/credentials && n8n import:workflow --separate --input=/demo-data/workflows"
    volumes:
      - ./n8n/demo-data:/demo-data
    depends_on:
      postgres_n8n:
        condition: service_healthy

  # Main N8N service
  n8n:
    <<: *service-n8n
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/demo-data:/demo-data
      - ./shared:/data/shared
    depends_on:
      postgres_n8n:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: n8n-qdrant
    networks: ['n8n_network']
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  # Ollama for local LLM support
  ollama:
    <<: *service-ollama
    profiles: ["n8n-cpu"]

  # Ollama GPU version
  ollama-gpu:
    <<: *service-ollama
    profiles: ["n8n-gpu-nvidia"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Initialize Ollama with Llama model
  ollama-init:
    image: ollama/ollama:latest
    networks: ['n8n_network']
    container_name: ollama-pull-llama
    volumes:
      - ollama_storage:/root/.ollama
    entrypoint: /bin/sh
    environment:
      - OLLAMA_HOST=ollama:11434
    command:
      - "-c"  
      - "sleep 10; ollama pull llama3.2"
    profiles: ["n8n-cpu"]
    depends_on:
      - ollama