version: '3.4'

services:
  api:
    volumes:
      # Logo replacement - mount to both public and dist paths
      - ./client/public/assets/logo.svg:/app/client/public/assets/logo.svg
      - ./client/public/assets/logo.svg:/app/client/dist/assets/logo.svg
      # Index HTML replacement for proper branding
      - ./client/index.html:/app/client/dist/index.html