services:
  api:
    container_name: nxsGPT
    ports:
      - "3080:3080"
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: api-build
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - MONGO_URI=mongodb://mongodb:27017/nxsGPT
      - APP_TITLE=nxsGPT
    volumes:
      - ./.env:/app/.env
      - ./librechat.yaml:/app/librechat.yaml
      - ./client/public/assets:/app/client/public/assets
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs

  mongodb:
    container_name: nxsgpt-mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth